# Generated by Django 5.2.1 on 2025-05-21 00:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Estado')),
            ],
            options={
                'verbose_name': 'Estado de Prestación',
                'verbose_name_plural': 'Estados de Prestación',
            },
        ),
        migrations.RemoveField(
            model_name='prestacion',
            name='fecha_prestacion',
        ),
        migrations.AddField(
            model_name='prestacion',
            name='fecha_calculo',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Cálculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestacion',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='prestacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='prestacion',
            name='periodo_fin',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 0, 51, 1, 527298, tzinfo=datetime.timezone.utc), verbose_name='Fin del Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestacion',
            name='periodo_inicio',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 0, 51, 59, 95352, tzinfo=datetime.timezone.utc), verbose_name='Inicio del Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestacion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones', to='rrhh.estadoprestacion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Renuncia', 'Renuncia'), ('Despido Justificado', 'Despido Justificado'), ('Despido Injustificado', 'Despido Injustificado')], max_length=100, verbose_name='Tipo de Liquidación')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Calculada', 'Calculada'), ('Pagada', 'Pagada')], default='Pendiente', max_length=50, verbose_name='Estado')),
                ('fecha_calculo', models.DateField(auto_now_add=True, verbose_name='Fecha de Cálculo')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('indemnizacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Indemnización')),
                ('vacaciones_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vacaciones Pendientes')),
                ('aguinaldo_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aguinaldo Proporcional')),
                ('bono14_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bono 14 Proporcional')),
                ('total_ingresos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Ingresos')),
                ('total_deducciones', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Deducciones')),
                ('total_liquidacion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Liquidación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('dias_totales', models.PositiveIntegerField(verbose_name='Días Totales')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Disfrutado', 'Disfrutado'), ('Pagado', 'Pagado')], default='Pendiente', max_length=50, verbose_name='Estado')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Vacaciones',
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
